apiVersion: apps/v1
kind: Deployment
metadata:
  name: #{Deployment}#
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: #{Deployment}#
  template:
    metadata:
      labels:
        app: #{Deployment}#
        type: #{Deployment}#
    spec:
      containers:
        - name: #{Deployment}#
          image: iboslimitedbd/#{Deployment}#:#{Build.BuildId}#
          resources:
            requests:
              memory: "64Mi"
            limits:
              memory: "3Gi"
          # Environment variable section
          env:
            - name: #{AppEnvName}#
              value: #{AppEnvValue}#
            - name: "ConnectionString"
              value: #{ConnectionString}#
            - name: "blob_connection"
              value: #{blob_connection}#
            - name: "TZ"
              value: #{Asia/Dhaka}#
      imagePullSecrets:
        - name: dockercred
      terminationGracePeriodSeconds: 60

---
apiVersion: v1
kind: Service
metadata:
  name: #{Deployment}#
spec:
  selector:
    app: #{Deployment}#
  ports:
    - port: 80
      # targetPort: 80
  # type: LoadBalancer
  # loadBalancerIP: 10.17.217.194

  #Ingress SSL with custom path Configurations
