using System;
using System.Collections.Generic;

namespace PeopleDesk.Data.Entity
{
    public partial class Account
    {
        public long IntAccountId { get; set; }
        public string StrAccountName { get; set; }
        public string StrShortCode { get; set; }
        public string StrOwnerName { get; set; }
        public string StrAddress { get; set; }
        public string StrMobileNumber { get; set; }
        public string StrNid { get; set; }
        public string StrBin { get; set; }
        public string StrEmail { get; set; }
        public string StrWebsite { get; set; }
        public long? IntLogoUrlId { get; set; }
        public long IntUrlId { get; set; }
        public long IntCountryId { get; set; }
        public long? IntOwnerEmployeeId { get; set; }
        public string StrCurrency { get; set; }
        public bool IsInternCloseMenual { get; set; }
        public bool IsProbationaryCloseMenual { get; set; }
        public bool IsEmployeeCodeAutoGenerated { get; set; }
        public bool IsBlock { get; set; }
        public bool? IsTax { get; set; }
        public bool? IsProvidentFund { get; set; }
        public bool? IsLoan { get; set; }
        public bool? IsActive { get; set; }
        public DateTime? DteExpireDate { get; set; }
        public long IntAccountPackageId { get; set; }
        public string StrAccountPackageName { get; set; }
        public long IntMinEmployee { get; set; }
        public long IntMaxEmployee { get; set; }
        public decimal NumPrice { get; set; }
        public decimal? NumPackageFileStorageQuaota { get; set; }
        public bool IsFree { get; set; }
        public bool IsLoggedInWithOtp { get; set; }
        public DateTime DteDateOfOnboard { get; set; }
        public decimal? NumFileStorageQuaota { get; set; }
        public DateTime DteCreatedAt { get; set; }
        public long? IntCreatedBy { get; set; }
        public DateTime? DteUpdatedAt { get; set; }
        public long? IntUpdatedBy { get; set; }
        public bool? IsOvertimeAutoCalculated { get; set; }
    }
}
